import "./assets/css/style.css";
import CommonLayout from "./Components/Common/CommonLayout";

export const metadata = {
  title: "Home Page | NextJs",
  description: "Generated by create next app Home Page",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CommonLayout>
          {children}
        </CommonLayout>
      </body>
    </html>
  );
}
