import React from 'react'
import About from '../Components/About'

export const metadata = {
  title: "About Us Page | NextJs",
  description: "Generated by create next app Home Page",
};

export default function page() {
   
  return (
    <div>
        <About/>
    </div>
  )
}
